version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
    - dependency-name: "@types/node"
      versions:
      - 15.0.0
  - package-ecosystem: npm
    directory: "/examples/viewer"
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: "/examples/anvil_saver"
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: "/examples/place_end_crystal"
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: "/examples/pathfinder"
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: "/examples/screenshot-with-node-canvas-webgl"
    schedule:
      interval: weekly
