sonar.organization=lightyagami28
sonar.projectKey=LightYagami28_mineflayer
sonar.projectName=mineflayer
sonar.sources=index.js,index.d.ts,lib,examples
sonar.tests=test
sonar.test.inclusions=test/**/*.js
sonar.exclusions=**/node_modules/**,server_jars/**,docs/**,**/*.min.js
sonar.sourceEncoding=UTF-8
